1.HERE IN LINE2 SINCE V_SAL IS DECLARED IN LINE 3 SO V_BONUS WILL NOT BE DECLARED AS ITS DATATYPE IS NOT KNOWN. 
2.EVEN IF WE CHANGE THE SEQUENCE OF LINE 2 AND LINE 3 WE WILL GET ERROR LIKE MULTIPLE RECORDS FETCHED FOR MGR_CODE=100006:
